# docker run --detach --restart never --user nobody:nogroup --volumes ./data/words.txt:/app/words.txt:ro --volumes ./src/anagrams.py:/app/script.py:ro --workdir /app/ index.docker.io/library/python:alpine python3 script.py
services:
  anagrams:
    command:
    - python3
    - script.py
    image: index.docker.io/library/python:alpine
    restart: "no"
    user: nobody:nogroup
    volumes:
    - ./data/words.txt:/app/words.txt:ro
    - ./src/anagrams.py:/app/script.py:ro
    working_dir: /app/
version: "2.0"
