#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anagrams-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits: 
      storage: 1Gi
    requests: 
      storage: 1Gi
#  storageClassName: gp2
  storageClassName: anagrams-sc
