#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: anagrams-secret
stringData:
  DATA_FILE: words.txt
  URL: https://raw.githubusercontent.com/Viviane-maker/santander-anagrams/docker/data/words.txt
type: Opaque
