#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: anagrams
spec:
  template:
    spec:
      containers:
        - 
          image: docker.io/library/python:alpine
          name: anagrams
          volumeMounts:
            - 
              mountPath: /data/
              name: anagrams
              readOnly: true
      initContainers:
        -
          args:
            - set -x ; rm -f ${DATA_FILE} ; wget ${URL}
          command:
            - sh
            - -c
          env:
            -
              name: DATA_FILE
              valueFrom:
                secretKeyRef:
                  key: DATA_FILE
                  name: anagrams
            -
              name: URL
              valueFrom:
                secretKeyRef:
                  key: URL
                  name: anagrams
          image: busybox
          name: initcontainer
          volumeMounts:
            -
              mountPath: /data/
              name: anagrams
              readOnly: false
          workingDir: /data/
      restartPolicy: Never
      volumes:
        - 
          name: anagrams
          persistentVolumeClaim:
            claimName: anagrams
            readOnly: false
          
