name: CI
on:
  push:
    branches:
    - main
jobs:
  docker-compose:
    runs-on: ubuntu-18.04
    steps:
    - name: code-checkout
      uses: actions/checkout@v2
    - name: test-compose
      run: docker-compose up
