#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: anagrams-job
spec:
  template:
    spec:
      containers:
        - 
          image: academiaonline/anagrams:latest
          imagePullPolicy: Always
          name: anagrams-container
          volumeMounts:
            - 
              mountPath: /data/
              name: anagrams-volume
              readOnly: true
      imagePullSecrets:
        -
          name: docker-login
      initContainers:
        -
          args:
            - set -x ; rm -f ${DATA_FILE} ; wget ${URL}
          command:
            - sh
            - -c
          env:
            -
              name: DATA_FILE
              valueFrom:
                secretKeyRef:
                  key: DATA_FILE
                  name: anagrams-secret
            -
              name: URL
              valueFrom:
                secretKeyRef:
                  key: URL
                  name: anagrams-secret
          image: busybox
          name: anagrams-initcontainer
          volumeMounts:
            -
              mountPath: /data/
              name: anagrams-volume
              readOnly: false
          workingDir: /data/
      restartPolicy: Never
      volumes:
        - 
          name: anagrams-volume
          persistentVolumeClaim:
            claimName: anagrams-pvc
            readOnly: false
          
