#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anagrams-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: anagrams-sc
  hostPath:
    path: /tmp/anagrams
    type: DirectoryOrCreate
